SciML/SciMLBase.jl

Project.toml
src/solutions/solution_interface.jl

Found in https://github.com/SciML/DiffEqOperators.jl/pull/322
Ambiguity tested locally

Fix missing method

---

src/problems/sde_problems.jl

I made a small mistake in my previous commit, now it is fixed.

Fix argument ordering typo

---

src/ensemble/ensemble_solutions.jl

Was introduced in https://github.com/SciML/SciMLBase.jl/pull/33.

Remove `@show`

---

.github/workflows/Downstream.yml
src/ensemble/ensemble_analysis.jl
test/ensemble_tests.jl
test/runtests.jl

Fixes https://github.com/SciML/DifferentialEquations.jl/issues/731 locally at least. CC @augustinas1

fix mean and cov for integer solution values in Ensembles

---

src/ensemble/ensemble_analysis.jl
test/downstream/ensemble_zero_length.jl

Fixes https://github.com/SciML/SciMLBase.jl/issues/35

two argument cov 

---

src/solutions/ode_solutions.jl
src/solutions/solution_interface.jl
test/downstream/symbol_indexing.jl

https://github.com/SciML/SciMLBase.jl/issues/83
@ChrisRackauckas

Remove old unreachable code

---

src/solutions/solution_interface.jl
test/downstream/symbol_indexing.jl

Fixes https://github.com/SciML/SciMLBase.jl/issues/86
Avoids StackOverflow error with invalid index
@ChrisRackauckas @YingboMa

Throw error with invalid symbol indexing

---

src/problems/basic_problems.jl

Related to https://github.com/SciML/GalacticOptim.jl/pull/150

Add `sense` field to OptimizationProblem

---

src/SciMLBase.jl
src/problems/basic_problems.jl

Fixes https://github.com/SciML/DiffEqFlux.jl/issues/600

Make OptimizationFunctions AbstractSciMLFunctions

---

src/solutions/dae_solutions.jl
src/solutions/ode_solutions.jl
src/solutions/rode_solutions.jl

Part of https://github.com/SciML/DifferentialEquations.jl/issues/786

Fix inference specialization in interpolations

---

src/solutions/solution_interface.jl
test/downstream/symbol_indexing.jl

Needs https://github.com/JuliaSymbolics/Symbolics.jl/pull/353 and https://github.com/SciML/ModelingToolkit.jl/pull/1222

Add vector symbolic support

---

src/solutions/ode_solutions.jl
test/downstream/Project.toml
test/downstream/unitful_interpolations.jl
test/runtests.jl

Fixes https://github.com/SciML/OrdinaryDiffEq.jl/issues/1514

Loosen element types to allow unitful in interpolations

---

src/utils.jl

Fixes https://github.com/SciML/SciMLBase.jl/issues/123

Fix warning kwargs

---

src/interpolation.jl
test/downstream/Project.toml
test/downstream/integer_idxs.jl
test/runtests.jl

Fixes https://github.com/SciML/Sundials.jl/issues/298

Fix fallback interpolations on idxs = integer

---

src/scimlfunctions.jl

I'll make a separate PR for other function types as it would be good to get this one into master for @TorkelE

adds observed field for DiscreteFunctions

---

src/solutions/ode_solutions.jl

One step towards fixing https://github.com/SciML/ModelingToolkit.jl/issues/1448

Abstract the ODESolution call overloads

---

src/tabletraits.jl
test/runtests.jl
test/traits.jl

Fixes https://github.com/SciML/SciMLBase.jl/issues/156

Fix the trait abstract type: only declare timeseries models as tables

---

docs/src/index.md

Please check if I removed the correct duplicate.

Remove double SciMLBase

---

Project.toml
src/SciMLBase.jl
src/problems/basic_problems.jl
src/problems/problem_traits.jl
src/problems/problem_utils.jl
src/solutions/basic_solutions.jl

By unanimous decision in the slack chat https://julialang.slack.com/archives/CN04R7WKE/p1653885583550209
16 upvotes, 0 downvotes.

Deprecate QuadratureProblem for IntegralProblem

---

src/scimlfunctions.jl

Part of solving https://github.com/SciML/Optimization.jl/issues/272
Purposefully not documented as it's shouldn't be considered public API

Allow for exprs in the OptimizationFunction

---

src/utils.jl

Specialize on parameterless_type

---

src/ensemble/basic_ensemble_solve.jl
test/downstream/ensemble_first_batch.jl
test/runtests.jl

This PR implements the proposed fix in https://github.com/SciML/SciMLBase.jl/issues/190.
It also adds a downstream test for this particular problem.

Fixes SciML/SciMLBase.jl#190 and add corresponding test

---

src/problems/basic_problems.jl
src/scimlfunctions.jl

Fixes https://github.com/SciML/Optimization.jl/issues/291

Complete OptimizationFunction and OptimizationProblem docstrings

---

src/integrator_interface.jl
test/downstream/integrator_indexing.jl
test/runtests.jl

Fixes https://github.com/SciML/ModelingToolkit.jl/issues/1470

Add `Base.getindex` methods for `DEIntegrator`

---

src/integrator_interface.jl
test/downstream/integrator_indexing.jl

Add `set_u!` method

---

src/scimlfunctions.jl

This will allow MTK (and others) to do track relationships between symbolic variables and states.

add sys field to function types

---

src/solutions/solution_interface.jl

minor cleanups to recipe

---

.github/workflows/Downstream.yml
src/SciMLBase.jl
src/problems/ode_problems.jl
src/remake.jl
src/utils.jl

This is a big move with a big potential payoff. Fingers crossed.

Enable no recompilation by default for ODEs with Vector{Float64}

---

src/scimlfunctions.jl

This PR adds the possibility of adding a Hessian of the Lagrangian to `OptimizationSystem`, i.e., a function that directly computes
$\dfrac{d^2}{dx^2} \big( \sigma f(x) + \lambda^T c(x) \big)$
rather than assembling this from individual constraint Hessians.
Many solvers, including Ipopt, MadNLP.jl and `Optim.IPNewton` want this function.
ref
- https://github.com/SciML/Optimization.jl/issues/343

add Hessian of Lagrangian to OptimizationFunction

---

src/scimlfunctions.jl

Fixes https://github.com/ChrisRackauckas/universal_differential_equations/issues/49

Improve definition of `f`

---

src/solutions/basic_solutions.jl

Complete move from `hasfield` to `hasproperty` in `wrap_sol`

---

src/integrator_interface.jl
src/scimlfunctions.jl
src/solutions/solution_interface.jl
test/downstream/integrator_indexing.jl
test/downstream/symbol_indexing.jl

Indexing of parameters

---

src/solutions/solution_interface.jl
test/downstream/symbol_indexing.jl

Fix parameter access from solution

---

src/remake.jl
src/utils.jl

Infrastructure for remaking with symbols where appropriate

remake with symbols infrastructure

---

Project.toml
src/alg_traits.jl
src/solve.jl

Fixes https://github.com/SciML/Optimization.jl/issues/310

Add optimization algs traits

---

Project.toml
src/alg_traits.jl
src/solve.jl
test/solver_missing_error_messages.jl

Should be the last one needed to finish it up.

Add `allowsconstraints` trait for `solve(::OptimizationProblem)`

---

src/utils.jl

I found this while reading https://sciml.ai/news/2022/10/08/error_messages/ - nice post so far, by the way :slightly_smiling_face:

fix typo in error message

---

src/integrator_interface.jl
src/solutions/solution_interface.jl
test/downstream/integrator_indexing.jl
test/downstream/symbol_indexing.jl

Reverts SciML/SciMLBase.jl#272 It's a breaking change.

Revert "Fix integrator parameter indexing, enable tests"

---

README.md
docs/make.jl

I just updated the README and make.jl links. There are other links to scimlbase docs in the internal files, but I did not want to muck around with those links till I got some direction from one of the system owners.

updated README and make.jl as per sciml template.

---

src/integrator_interface.jl
src/solutions/solution_interface.jl

Since that's what we're actually trying to access.

In `getobserved` check `observed`, not `syms`

---

src/retcodes.jl

Adds retcodes for optimization problems

---

src/integrator_interface.jl
src/solutions/solution_interface.jl
test/downstream/integrator_indexing.jl
test/downstream/symbol_indexing.jl

Reverts SciML/SciMLBase.jl#279
See https://github.com/SciML/SciMLBase.jl/pull/284 . This is actually the behavior that we wanted. We just need to test this better to make it more solidified.

Revert "Revert "Fix integrator parameter indexing, enable tests""

---

test/downstream/integrator_indexing.jl

Fix integrator indexing test

---

src/remake.jl

- Merge after #310 and https://github.com/SciML/ModelingToolkit.jl/pull/1941
- closes #297

Use process_p_u0_symbolic from MTK

---

src/problems/steady_state_problems.jl

Fixes https://github.com/SciML/SteadyStateDiffEq.jl/issues/44

Fix documentation of steady state problem

---

src/problems/basic_problems.jl

See https://github.com/SciML/Optimization.jl/issues/8#issuecomment-1339271385 and https://github.com/SciML/Optimization.jl/pull/438.

Move ObjSense from Optimization.jl into SciMLBase.jl

---

src/problems/basic_problems.jl

Fix sentence

---

src/solutions/optimization_solutions.jl

adds solve_time to opt. solution

---

Project.toml
src/utils.jl

Fixes https://github.com/SciML/diffeqr/issues/39

Fix RCall function argument reading generation

---

src/utils.jl

Fixes to be robust to https://github.com/JuliaInterop/RCall.jl/pull/472. Right now it's a bit janky, but this should then change to being a proper dispatch with weak dependencies in the near future.

Make RCall handling robust to function change

---

src/problems/basic_problems.jl

Related to [this discourse post](https://discourse.julialang.org/t/x-argument-in-optimization-optimizationproblem/92971/2).

Fixed typo in OptimizationProblem docstring

---

src/SciMLBase.jl
src/debug.jl
src/solve.jl

Superscedes https://github.com/SciML/SciMLBase.jl/pull/368

Throw SciML-specific information using error hinting

---

src/solutions/dae_solutions.jl

These methods don't support symbolic indexing, and don't do anything.

Remove bad solution indexing methods.

---

Project.toml
src/solutions/solution_interface.jl

looks like it was a merge error. Fixes https://github.com/SciML/SciMLBase.jl/issues/395

Remove duplicated symbolic indexing interface

---

src/solutions/solution_interface.jl

Fixes https://github.com/SciML/SciMLBase.jl/issues/398

Fix duplicated code

---

src/scimlfunctions.jl

Fixes https://github.com/SciML/TruncatedStacktraces.jl/issues/4

Fix OptimizationFunction simplified stack trace

---

.github/workflows/Downstream.yml
src/integrator_interface.jl

Fix https://github.com/SciML/ModelingToolkit.jl/actions/runs/5008816715/jobs/8977085888?pr=2161#step:6:875

Don't over specialize dae init

---

Project.toml
src/ensemble/ensemble_analysis.jl
test/aqua.jl
test/runtests.jl

This PR adds aqua tests to the test suite.

Add aqua tests

---

src/alg_traits.jl

Ported over from https://github.com/SciML/DiffEqBase.jl/pull/859

Add alg_order function stub

---

Project.toml
src/SciMLBase.jl

[WIP] Fix specialization error

---

Project.toml
src/problems/bvp_problems.jl
src/scimlfunctions.jl

Try to fix ```BVPFunction``` errors

Fix BVPFunction errors

---

src/ensemble/ensemble_problems.jl

Fixup for #519 (I didn't see these entry points)
Does not fix https://github.com/SciML/diffeqpy/pull/122#issuecomment-1768836371.

Add input preparation to ensemble problems

---

ext/SciMLBaseRCallExt.jl

Reverts SciML/SciMLBase.jl#523

Revert "Switch R to using numargs"

---

src/problems/basic_problems.jl
src/scimlfunctions.jl
src/solve.jl

Fixes https://github.com/SciML/Optimization.jl/issues/498 https://github.com/SciML/Optimization.jl/issues/490

Update `OptimizationFunction`, `OptimizationProblem` and `solve` docstrings

---

src/ensemble/ensemble_analysis.jl

fix: fix EnsembleAnalysis methods for RAT v3

---

src/ensemble/ensemble_analysis.jl

fix: fix EnsembleAnalysis methods for RAT v3 (again)

---

.github/workflows/Downgrade.yml

[skip ci] update downgrade CI repo

[skip ci] update downgrade CI repo

---

src/SciMLBase.jl

Adds originator for Enzyme AD.

EnzymeOriginator

---

src/scimlfunctions.jl

OptFunc docstring minor updates

---

Project.toml
src/solutions/solution_interface.jl

Sorry, it looks like a debug statement was accidentally pushed in #655.

remove debug statement

---

ext/SciMLBaseZygoteExt.jl
src/problems/problem_interface.jl
src/remake.jl
test/downstream/modelingtoolkit_remake.jl
test/downstream/problem_interface.jl

Close #660 
Close #661 
Close https://github.com/SciML/ModelingToolkit.jl/issues/2637

fix: fix remake and indexing

---

src/problems/basic_problems.jl

I'm very confused at what was causing the CI issues, but the CI issues clearly exist.

revert https://github.com/SciML/SciMLBase.jl/pull/681#issuecomment-2088725391

---

Project.toml

Bump Makie compat and patch version

---

test/downstream/modelingtoolkit_remake.jl

test: fix typo in variable name

---

src/solutions/solution_interface.jl

nfc. Found while debugging an interpolation issue with plotting.

slightly simplify plotting interface

---

test/downstream/modelingtoolkit_remake.jl

test: remove hybrid systems from downstream tests

---

ext/SciMLBaseZygoteExt.jl

fix: temporarily remove ambiguous adjoint

---

test/downstream/problem_interface.jl

fix: fix downstream CI

---

src/remake.jl

feat: add `remake_initializeprob`

---

src/remake.jl
test/remake_tests.jl

Resolves #735 
adds a `remake` function for `SDEFunction` in the process

add `g` kwarg to `remake(::SDEProblem)`

---

src/solutions/ode_solutions.jl
src/solutions/solution_interface.jl
test/downstream/comprehensive_indexing.jl
test/downstream/integrator_indexing.jl
test/downstream/solution_interface.jl

fix: handle more plotting cases, add more comprehensive tests

---

src/clock.jl
test/runtests.jl
test/serialization_tests.jl

feat: support serialization of clocks

---

Project.toml
src/interpolation.jl
src/problems/optimization_problems.jl
src/scimlfunctions.jl
src/utils.jl

Add `fg` and `fgh` fields to `OptimizationFunction`

---

src/solve.jl

Fixes https://github.com/SciML/Optimization.jl/issues/795

Update `solve(::OptimizationProblem)` docstring

---

Project.toml
src/alg_traits.jl

Add more traits for Optimization solvers

---

src/alg_traits.jl

We need this for https://github.com/SciML/SciMLSensitivity.jl/pull/1096

add `alg_interpretation` trait

---

src/solutions/ode_solutions.jl
test/downstream/comprehensive_indexing.jl

From https://github.com/SciML/ModelingToolkit.jl/issues/3004. This is only half the fix.

fix: don't interpolate discretes if not interpolating discrete symbolic

---

test/downstream/solution_interface.jl

test: fix initialization of lorenz system in test

---

test/downstream/problem_interface.jl

fix: fix usage of getters of different system

---

src/solutions/ode_solutions.jl

fix: fix edge case in interpolation check

---

src/integrator_interface.jl

Fixes https://github.com/SciML/SciMLBase.jl/issues/822

Hotfix ambiguity

---

src/scimlfunctions.jl

no idea how CI missed this the first time

fix `W__prototype` typo

---

src/solutions/solution_interface.jl

fix: fix `symbolic_container` and `parameter_values` for solutions

---

src/solutions/solution_interface.jl

feat: add `plottable_indices`

---

src/solutions/solution_interface.jl

fix: hotfix `plottable_indices`

---

src/scimlfunctions.jl

feat: add `initialization_data` to all `SciMLFunction`s

---

src/scimlfunctions.jl
test/downstream/problem_interface.jl

fix: fix some SciMLFunction constructors

---

src/scimlfunctions.jl

fix: fix `DynamicalODEFunction` constructor

---

src/alg_traits.jl

feat: add `allows_late_binding_tstops` algorithm trait

---

src/problems/dae_problems.jl

feat: add `constructorof` for `DAEProblem`

---

src/initialization.jl

fix: fix `CheckInit` error message

---

Project.toml
src/problems/dde_problems.jl
src/problems/discrete_problems.jl
src/problems/implicit_discrete_problems.jl
src/problems/optimization_problems.jl
src/problems/sde_problems.jl

Sorry this should have been done right the first time, my brain has been a bit fried from this terrible cold :-(

fix constructors for Alias specifiers

---

src/remake.jl
test/downstream/modelingtoolkit_remake.jl

Close https://github.com/SciML/ModelingToolkit.jl/issues/3326

fix: fix `remake` not able to substitute values

---

Project.toml
src/solutions/ode_solutions.jl

SavedSubsystem is an internal and should not be exposed to the user.

Remove savedsubsystem mention

---

src/remake.jl
test/downstream/modelingtoolkit_remake.jl

Close https://github.com/SciML/ModelingToolkit.jl/issues/3281
Close https://github.com/SciML/ModelingToolkit.jl/issues/2660

fix: handle array unknown provided as `Symbol` to `remake`

---

src/scimlfunctions.jl

For arguments to `OptimizationFunction`

Fix markdown list in docstring

---

src/problems/problem_utils.jl
src/problems/steady_state_problems.jl
src/remake.jl
test/downstream/modelingtoolkit_remake.jl
test/remake_tests.jl

Close https://github.com/SciML/ModelingToolkit.jl/issues/3430

feat: add dedicated `remake` method for `SteadyStateProblem`

---

src/problems/implicit_discrete_problems.jl
test/downstream/modelingtoolkit_remake.jl

needed to mutate successfully in `initialize_dae`

Add ConstructionBase constructor for ImplicitDiscreteProblem

---

src/remake.jl

fix: fix `remake(::SteadyStateProblem)`

---

src/remake.jl

fix: fix type inference in `remake`

---

src/initialization.jl
test/downstream/initialization.jl

feat: add `metadata` to `OverrideInitData`

---

.github/workflows/Downstream.yml

ci: split MTK downstream workflow

---

test/downstream/solution_interface.jl

test: fix hack in symbolic `save_idxs` test

---

src/problems/integral_problems.jl

Fixes https://github.com/SciML/SciMLBase.jl/issues/1018

Better deprecation message for nout and nbatch

---

src/problems/linear_problems.jl

Add correct function to LinearProblem docstring

---

ext/SciMLBaseChainRulesCoreExt.jl

Add adjoint rrule for IntervalNonlinearProblem constructor

---

src/scimlfunctions.jl

Should fix https://github.com/SciML/SciMLBase.jl/issues/1037

Add missing type parameter for unwrapped_f of NoSpecialize

---

test/downstream/observables_autodiff.jl

Uncomment parameter observables_autodiff.jl part

---

test/downstream/comprehensive_indexing.jl
test/downstream/modelingtoolkit_remake.jl
test/downstream/problem_interface.jl

test: fix SII test group

---

src/solve.jl

Fixes https://github.com/SciML/Optimization.jl/issues/587

Add reference to optimizationsolution in the solve docs

---

test/downstream/modelingtoolkit_remake.jl

test: fix jump affects in MTK remake test

---

src/problems/ode_problems.jl

Should fix https://github.com/trixi-framework/Trixi.jl/pull/2522

Fix SplitODEProblem fallback for non-DiffCache

---

ext/SciMLBaseMeasurementsExt.jl

Fix MeasurementsExt

---

src/errors.jl

feat: add `save_discretes` as an allowed `solve` kwarg
