src/scimlfunctions.jl

Add helper functions for AbstractSciMLFunction

---

src/solutions/solution_interface.jl

```julia
using ModelingToolkit, OrdinaryDiffEq
@parameters t σ ρ β
@variables x(t) y(t) z(t)
D = Differential(t)
eqs = [D(x) ~ σ*(y-x),
D(y) ~ x*(ρ-z)-y,
D(z) ~ x*y - β*z]
lorenz1 = ODESystem(eqs,name=:lorenz1)
lorenz2 = ODESystem(eqs,name=:lorenz2)
@variables a
@parameters γ
connections = [0 ~ lorenz1.x + lorenz2.y + a*γ]
connected = ODESystem(connections,t,[a],[γ],systems=[lorenz1,lorenz2])
u0 = [lorenz1.x => 1.0,
lorenz1.y => 0.0,
lorenz1.z => 0.0,
lorenz2.x => 0.0,
lorenz2.y => 1.0,
lorenz2.z => 0.0,
a => 2.0]
p  = [lorenz1.σ => 10.0,
lorenz1.ρ => 28.0,
lorenz1.β => 8/3,
lorenz2.σ => 10.0,
lorenz2.ρ => 28.0,
lorenz2.β => 8/3,
γ => 2.0]
tspan = (0.0,100.0)
prob = ODEProblem(connected,u0,tspan,p)
sol = solve(prob,Rodas5())
sol[lorenz1.x]
sol[lorenz1.x,2]
sol[lorenz1.x,:] …
```

Indexing hooks for symbolic DSLs

---

src/SciMLBase.jl
src/problems/dde_problems.jl
src/scimlfunctions.jl

Hey @ChrisRackauckas,
Following up on last semester, this PR has the plumbing necessary for `SecondOrderDDEProblem` that seems to be working well in Photron the last few weeks. It mirrors the structure of `SecondOrderODEProblem`, with the necessary changes in order to support a history function as well as 2 initial conditions. [DelayDiffEq.jl](https://github.com/SciML/DelayDiffEq.jl) requires a one-line change for this to work, because before it would only wrap the concrete `DDEFunction` rather than any `AbstractDDEFunction`: https://github.com/SciML/DelayDiffEq.jl/pull/203
Once Photron reaches stability, I can add its Lienard-Wiechert solver to [DiffEqProblemLibrary.jl/src/dde](https://github.com/SciML/DiffEqProblemLibrary.jl/tree/master/src/dde) as an example of how to use this problem …

SecondOrderDDEProblem (and underlying DynamicalDDEProblem)

---

src/solutions/nonlinear_solutions.jl

I have kept all `u`, `left` & `right` for compatibility issues. I will set `u` to `left` in case of bracketing methods. Should I also set `left = u` implicitly?
Ref: https://github.com/JuliaComputing/NonlinearSolve.jl/pull/28
@ChrisRackauckas @YingboMa , please review.

Add left & right params for Bracketing methods

---

src/SciMLBase.jl
src/problems/sde_problems.jl
src/scimlfunctions.jl

I've added the DynamicalSDEProblem and DynamicalSDEFunction. I'm not entirely sure if these are necessary since they're almost direct copies of the existing SplitSDEProblem/Function.
The reason for this PR is for [#259 in StochasticDiffEq](https://github.com/SciML/StochasticDiffEq.jl/issues/259). I've also submitted a PR to StochasticDiffEq that uses these functions with the BAOAB algorithm.
I don't understand the existence of the SplitSDEProblem type since its constructors just create the original SDEProblem instead, so as far as I can tell, the SplitSDEProblem itself is never used. I followed this trend for the new DynamicalSDEProblem but perhaps it's not necessary.

Add DynamicalSDEFunction and Problem

---

Project.toml
src/solutions/optimization_solutions.jl

This allows for using the new OptimizationSolution as the underbelly for DiffEqFlux.jl in a non-breaking way. This is going to be a very "soft" change, as in `.minimizer` will still work without throwing an error, and in about a year we can add a depwarn. But we will change the documentation and tests almost immediately. This will let users slowly phase out the use of `.minimizer`, and we can throw a depwarn on code about a year. Naturally it should all be moving from `sciml_train` to direct GalacticOptim use over that time.

Start the soft deprecation of minimizer

---

src/ensemble/ensemble_solutions.jl
src/integrator_interface.jl
src/problems/problem_utils.jl
src/scimlfunctions.jl
src/solutions/optimization_solutions.jl
src/solutions/solution_interface.jl
src/utils.jl
test/display.jl
test/runtests.jl

Resolves https://github.com/SciML/DifferentialEquations.jl/issues/728#issuecomment-789047602 by cleaning up the display methods.
Currently, displaying an `ODEProblem` _in a display that does not support color_ looks glitchy, e.g.:
```
[36mODEProblem[0m with uType [36mArray{Int64,1}[0m and tType [36mFloat64[0m. In-place: [36mtrue[0m
timespan: (0.0, 100.0)
u0: [1, 0]
```
Here, `[36m` etc are "colorize" commands, `[36m` means "cyan from now on", when read by a terminal that supports color.
Julia has a mechanism to solve such problems: `IOContext`. The `IO` (supertype of `IOContext`) argument to `Base.show`, `Base.summarize`, etc, contains extra information, including the `:color` flag, which the REPL sets to `true` if you are in a color terminal, and Pluto sets it to `false`, since …

Use IO in Base.summary, respect :color setting

---

src/problems/dde_problems.jl

I removed the `::Function` restriction as mentioned in https://github.com/SciML/SciMLBase.jl/issues/42#issuecomment-808923055

Fix ambiguities

---

src/operators/common_defaults.jl

This PR simply adds a 5-arg `mul!` for `AbstractDiffEqLinearOperator`.
I'd like this functionality to be able to compose more things together and facilitate in place computations of sums of ODE-like functions and linear operators, i.e. something like `f(u) + L * u`:
```julia
f(du, u, p, t) # some in-place function writes du <- f(u)
mul!(du, L, u, 1, 1) # du <- L * u + f(u)
```
I'm not sure this is the right way to add this, please let me know if I need to think more about it! 😅 My current thinking is that I could use that, but maybe there's just no need for it?  🤷

Add 5-arg `mul!`

---

src/ensemble/basic_ensemble_solve.jl

to work around https://github.com/JuliaLang/julia/issues/35800
which can cause very slow compile times in Julia 1.6. In Pumas, this change alone had the following effect on a single function call:
```julia
40.194758 seconds (83.73 M allocations: 6.623 GiB, 2.70% gc time, 99.99% compilation time)
```
```julia
2.916390 seconds (7.31 M allocations: 446.180 MiB, 3.71% gc time, 99.96% compilation time)
```
I'm erroring out in the empty case since it avoids the problem of determining the return type. I'd think that it's expected that the number of trajectories is positive. I actually think that part of the problem with `map` is that it has to consider the empty case but that is mostly speculation.

Change map for a for loop

---

src/ensemble/basic_ensemble_solve.jl
test/downstream/ensemble_zero_length.jl

`responsible_map` was leading to downstream issues where type signature of elements in ensemble solution don't match exactly.
https://github.com/SciML/DiffEqBase.jl/pull/510#issuecomment-629753607
Before
```
julia> @benchmark solve_ode(f, (a = 1, b = 1))
BenchmarkTools.Trial: 
memory estimate:  6.32 MiB
allocs estimate:  47533
--------------
minimum time:     6.613 ms (0.00% GC)
median time:      8.372 ms (0.00% GC)
mean time:        9.322 ms (7.21% GC)
maximum time:     26.238 ms (0.00% GC)
--------------
samples:          535
evals/sample:     1
```
now
```
BenchmarkTools.Trial: 
memory estimate:  6.32 MiB
allocs estimate:  47543
--------------
minimum time:     6.529 ms (0.00% GC)
median time:      7.636 ms (0.00% GC)
mean time:        8.178 ms (7.59% GC)
maximum time:     20.434 ms …
```

Relax type in the initialized array in responsible_map

---

src/SciMLBase.jl
src/operators/common_defaults.jl
src/operators/diffeq_operator.jl

As a continuation from https://github.com/SciML/SciMLBase.jl/pull/41#issuecomment-808957928
This moves the following from DiffEqOperators
- DiffEqScaledOperator
- AbstractDiffEqCompositeOperator (since it was required by subtyping)
- update_coefficients!
- getops (since it was needed for other functions)
- Base and LinearAlgebra overloads for DiffEqScaledOperator
This should be tested together with https://github.com/SciML/DiffEqOperators.jl/pull/363

Move `DiffEqScaledOperator`

---

src/ensemble/basic_ensemble_solve.jl

No point `sizehint!`-ing after already allocating the full vector.

Delete sizehint! in responsible_map

---

src/problems/ode_problems.jl

There was a small typo in a comment about DynamicalODEProblem.
Now the indices are in line with the [documentation](https://diffeq.sciml.ai/stable/types/dynamical_types/).
There seems to be similar problem with the Documentation of [HamiltonianProblem](https://github.com/SciML/DiffEqDocs.jl/issues/451).

fix typo in commit about DynamicalODEProblem

---

src/solutions/solution_interface.jl

`AbstractNoTimeSolution` is missing a method for `Base.getindex` with `Colon` as index.
This can lead otherwise to a `StackOverflowError` in a `SteadyStateAdjointProblem` through recursive calls to `Base.getindex(A::AbstractNoTimeSolution,sym)` when indexing the solution as `sol[:]`.

Add missing method for indexing with `Colon`

---

src/solutions/solution_interface.jl

This slaps a bandaid on the issue.  It would probably be good to add a test.

Fix plotting of solution when `saveat` is used

---

src/solutions/solution_interface.jl

FIxes https://github.com/SciML/DiffEqSensitivity.jl/pull/442#issue-684476791
Covers case where the given ODEFunction does not have `syms` or  `p` property.

`augment` function bug fix

---

src/solutions/solution_interface.jl

Match `issymbollike`  to [RecursiveArrayTools's implementation](https://github.com/SciML/RecursiveArrayTools.jl/blob/master/src/vector_of_array.jl#L22). 
Just spotted this bug. Didn't trigger any downstream tests in #66 unexpectedly.

Fix issymbollike special case not covered by downstream tests

---

src/scimlfunctions.jl

The constructor with no recompile was missing a couple of `Any` to match the number of fields in the struct.

add missing Any in constructor

---

src/remake.jl

This should enable the user to modify either an `AbstractEnsembleProblem` or the problem stored therein. There could be an issue if one tries to modify a field in the inner problem but the keyword is also in the `AbstractEnsembleProblem`, but I'll leave that up to your discretion if that's a real issue.

Add the ability to remake an `AbstractEnsembleProblem`

---

src/problems/basic_problems.jl

To avoid a much more cryptic error message

Throw an error if either `lb` or `ub` is provided but not both

---

src/operators/basic_operators.jl
test/diffeqoperator.jl

apparently `LinearAlgebra.factorize` can output types that are not `Factorization`s, but have defined left-division. so we should loosen type parameterization on `FactorizedDiffEqArrayOperator` to allow for `Diagonal`, `Bidiagonal`, and others. Would be good to have a flag in ArrayInterface that tells if a type has `ldiv!` defined. 
```julia
julia> using LinearAlgebra, SciMLBase; n=8;
julia> p = LinearProblem(Matrix(I,n,n), rand(n));
julia> A = p.A
DiffEqArrayOperator{Bool, Matrix{Bool}, typeof(SciMLBase.DEFAULT_UPDATE_FUNC)}(Bool[1 0 … 0 0; 0 1 … 0 0; … ; 0 0 … 1 0; 0 0 … 0 1], SciMLBase.DEFAULT_UPDATE_FUNC)
julia> factorize(A)
ERROR: MethodError: no method matching SciMLBase.FactorizedDiffEqArrayOperator(::Diagonal{Bool, Vector{Bool}})
Closest candidates are: …
```

problem with factorizing Identity

---

src/ensemble/ensemble_analysis.jl
src/ensemble/ensemble_solutions.jl
test/downstream/ensemble_zero_length.jl

Fixes #132
The following script can be used for a before/after comparison:
```julia
using OrdinaryDiffEq, Plots
logistic(du, u, p, t) = @. du = p * u * (1 - u)
prob = ODEProblem(logistic, [1e-2], (0.0, 2.5), [3.0])
prob_func(prob, i, repeat) = i < 100 ? remake(prob, u0=[0.9]) : remake(prob, u0=[1e-2 + 0.001*randn()])
eprob = EnsembleProblem(prob, prob_func=prob_func)
esol = solve(eprob, Tsit5(), trajectories=1000)
esum = EnsembleSummary(esol, 0.0:0.01:2.5, quantiles=[0.1, 0.9])
plot(esum)
```
Now, the plot recipe plots the median and quantiles and the resulting plot becomes more easily interpretable.
I did not add any new tests or adjust version numbers, so please let me know what should be done in these regards.

Add the median to EnsembleSummary and adjust the plot recipe

---

src/scimlfunctions.jl

This adds `observed` to all *Function types. If that is desirable / correct the other PR that just adds it for `DiscreteFunction`s can be closed. If not this can be closed and just that PR accepted (if it looks ok).

Add observed to functions

---

src/SciMLBase.jl

This is a different approach to achieving the intended outcome in #144. If `NoInit()` is defined in SciML base then it is possible to do the following 
```julia
function my_initialization(my_problem::SciMLBase.DEProblem, args...)
return
end
SciMLBase.solve(
my_problem,
solver;
initializealg = NoInit(),
)
```
It leaves it to the developer to be responsible that the residual is withing the specified tolerance of the solver but its a reasonable workaround to avoid a full OrdinaryDiffEq dependency.

move NoInit from OrdinaryDiffEq

---

Project.toml
src/problems/bvp_problems.jl
src/problems/dae_problems.jl
src/problems/dde_problems.jl
src/problems/discrete_problems.jl
src/problems/ode_problems.jl
src/problems/rode_problems.jl
src/problems/sdde_problems.jl
src/problems/sde_problems.jl
src/problems/steady_state_problems.jl

Apparently 
```
@doc doc"""
$(TYPEDEF)
```
is not supported, and so you can't do typedef with the Latex support.

Fix docstrings

---

src/problems/basic_problems.jl
src/solutions/basic_solutions.jl
src/solutions/dae_solutions.jl
src/solutions/nonlinear_solutions.jl
src/solutions/ode_solutions.jl
src/solutions/optimization_solutions.jl
src/solutions/rode_solutions.jl

QuadratureProblem and OptimizationProblem will need more work, but we can keep that as an issue for the future.

Add a bunch more docstrings to problems and solutions

---

Project.toml
docs/src/interfaces/DEAlgorithm.md
src/alg_traits.jl

@yingboma before I forget, what happens with Radau when `u0` is complex? That would fail right, so we should set `allowscomplex` to false on radau methods?

Expand the algorithm traits and document them

---

src/integrator_interface.jl

Include the actual values of `t`, `dt` and `dtmin` in the *dt <= dtmin* warning message to simplify the diagnostic.

More informative diagnostic for dt <= dtmin

---

src/problems/basic_problems.jl
src/scimlfunctions.jl

Fixes https://github.com/SciML/SciMLBase.jl/issues/159 and fixes https://github.com/SciML/SciMLBase.jl/issues/158

Improved OptimizationProblem, OptimizationFunction, and Quadrature docs

---

src/solutions/solution_interface.jl
test/runtests.jl
test/solution_interface.jl

Currently, I'm getting
```julia
julia> u = rand(1)
1-element Vector{Float64}:
0.994423898075866
julia> u[]
0.994423898075866
julia> SciMLBase.build_linear_solution(nothing, u, zeros(1), nothing)[]
ERROR: ArgumentError: invalid index: () of type Tuple{}
Stacktrace:
[1] to_index(i::Tuple{})
@ Base ./indices.jl:300
[2] to_index(A::Vector{Float64}, i::Tuple{})
@ Base ./indices.jl:277
[3] to_indices
@ ./indices.jl:333 [inlined]
[4] to_indices
@ ./indices.jl:325 [inlined]
[5] getindex
@ ./abstractarray.jl:1218 [inlined]
[6] getindex(::SciMLBase.LinearSolution{Float64, 1, Vector{Float64}, Vector{Float64}, Nothing, Nothing})
@ SciMLBase ~/.julia/dev/SciMLBase/src/solutions/solution_interface.jl:6
[7] top-level scope
@ REPL[7]:1
```
and after this change I'm getting
```julia
julia> …
```

Define single argument getindex method for AbstractNoTimeSolution

---

src/scimlfunctions.jl
src/utils.jl
test/display.jl
test/function_building_error_messages.jl
test/runtests.jl

Note that there is a broken case where `f` is `iip` and `jac` has `oop` and `iip` dispatches, but it throws a non-conforming error. That will take quite a bit of code to solve and is quite an edge case, so I'm not going to let that block this and will just keep as `@test_broken` with an issue open.

Throw early warning function argument errors

---

Project.toml
src/solutions/ode_solutions.jl
src/utils.jl

Now it will mention the methods that are available:
```julia
julia> ODEProblem(ftoomany, u0, tspan)
ERROR: All methods for the model function `f` had too many arguments. For example,
an ODEProblem `f` must define either `f(u,p,t)` or `f(du,u,p,t)`. This error
can be thrown if you define an ODE model for example as `f(du,u,p1,p2,t)`.
For more information on the required number of arguments for the function
you were defining, consult the documentation for the `SciMLProblem` or
`SciMLFunction` type that was being constructed.
A common reason for this occurance is due to following the MATLAB or SciPy
convention for parameter passing, i.e. to add each parameter as an arguemnt.
In the SciML convention, if you wish to pass multiple parameters, use a
struct or other collection to hold the …
```

More information in function argument errors

---

src/problems/basic_problems.jl
src/scimlfunctions.jl
src/solve.jl

Fixed trivial documentation bugs as I found them.

Typo fixes in Optimization.jl documentation

---

.gitignore
src/integrator_interface.jl
src/solutions/solution_interface.jl
test/downstream/integrator_indexing.jl
test/downstream/symbol_indexing.jl

I left the depreciation warning with `force = true` as it seems like this is something users should see (i.e. it doesn't only impact package developers who would see it in tests). 
I can turn it off though if that is preferred.

depreciate vars in plot recipe for idxs

---

src/solutions/ode_solutions.jl

As stated in #212, many functions in `ode_solutions.jl` are defined for `AbstractODESolution` objects, yet they return actual `ODESolution`s. This PR restricts these functions to `sol::ODESolution`.
The PR also adds a simpler constructor that shortens the code quite a bit: Instead of providing *all* types, one can now build an ODESolution with just `ODESolution{T, N}(u, u_analytic, ...)`.Please let me know if this is a desired change or not! If not I'll just remove the second commit of this PR again.

Restrict many ode_solutions.jl functions to actual `ODESolution`s

---

src/scimlfunctions.jl

The formatting in rendered docs depend on indentation of the first line of code
http://optimization.sciml.ai/stable/API/optimization_function/#SciMLBase.OptimizationFunction
Also fixes some math expressions that were not rendered correctly

Fix formatting of some docstrings

---

src/solutions/rode_solutions.jl

This allows the computation of `sol.u_analytic` for problems of type `AbstractSDDEProblem` or `AbstractRODEProblem` with `noise` given as a `NoiseFunction`.
Previously, `sol.W[i]` would be called at https://github.com/SciML/SciMLBase.jl/blob/8bab6d3bc11c8db65d73875a2ea0f43bd854dd87/src/solutions/rode_solutions.jl#L118 regardless of being a proper vector-like `NoiseProcess` or a `NoiseFunction`, which would error for the latter. Checking whether `sol.W` is a `sol.W isa AbstractDiffEqArray{T, N, nothing} where {T, N}` and calling `first(sol.W(sol.t[i]))` instead fixes the problem.
I also make sure to `empty!(sol.u_analytic)` before filling it to avoid inadvertently doubling its size from a possible previous call to `calculate_solution_errors!(sol)`.

SDE u_analytic with noise as NoiseFunction

---

src/scimlfunctions.jl

Fixes regression found in https://github.com/SciML/StochasticDiffEq.jl/pull/494 caused by https://github.com/SciML/SciMLBase.jl/pull/218

add sys field to function types I missed

---

Project.toml
src/SciMLBase.jl
src/problems/ode_problems.jl
src/remake.jl
src/scimlfunctions.jl

This is mostly for testing.
```julia
using OrdinaryDiffEq, SnoopCompile, Profile, ProfileView
function lorenz(du, u, p, t)
du[1] = 10.0(u[2] - u[1])
du[2] = u[1] * (28.0 - u[3]) - u[2]
du[3] = u[1] * u[2] - (8 / 3) * u[3]
end
@time begin
lorenzprob = ODEProblem{true, SciMLBase.AutoSpecialize}(lorenz, [1.0; 0.0; 0.0], (0.0, 1.0), Float64[])
sol = solve(lorenzprob, Rosenbrock23())
end
```
This is with a change to OrdinaryDiffEq.jl precompiling both. Currently it looks like this does not give any advantage (other than in allocations) over using the AutoSpecialize form. But it's good to keep this machinery around because it's completed and the speed of light version of such wrapping, so it can allow us to easily build fully complete pre-wrapped system image packages while not impacting the …

Allow for early wrapping

---

src/problems/problem_traits.jl

I didn't check, but unbound type parameters often cause performance issues, so this may not be merely cosmetic.

remove unbound type parameter

---

src/problems/bvp_problems.jl

modified:   src/problems/bvp_problems.jl cODEFunction -> ODEFunction
Not covered by tests. 
```
#Working:
BVProblem(ode!, bc!, initial_guess, tspan, p)
BVProblem{true}(ode!, bc!, initial_guess, tspan, p)
```
I'm not sure when and how enabling compilation affects start-up-time, but it could be a side effect of this fix.

cODEFunction -> ODEFunction (bug left from removing convert).

---

src/integrator_interface.jl
src/solutions/solution_interface.jl
test/downstream/integrator_indexing.jl
test/downstream/symbol_indexing.jl

- Indexing integrators with parameters was broken, fixed it
- This wasn't caught by tests because the tests were commented. When the feature was introduced it needed changes in MTK and would've failed CI.
- Closes #273

Fix integrator parameter indexing, enable tests

---

src/problems/basic_problems.jl

Adds field indicating integrality of the opt vars

---

src/retcodes.jl

Meant for https://github.com/SciML/NonlinearSolve.jl/pull/92

Add ReturnCodes for NonlinearSolve.jl

---

src/solutions/optimization_solutions.jl
src/solve.jl

The current entrypoint is
```julia
solve(prob::OptimizationProblem, alg, args...; kwargs...)
```
and this method needs to be defined:
```julia
__solve(prob::OptimizationProblem, alg::SomeAlg, args...; kwargs...)
```
which is still possible, if no cache interface is defined.
If a cache interface should be defined the following methods have to be defined:
```julia
supports_opt_cache_interface(alg::SomeAlg) = true
__solve(cache::SomeAlgsOptimizationCache)::AbstractOptimizationSolution
__init(prob::OptimizationProblem, alg::SomeAlg, args...; kwargs...)::SomeAlgsOptimizationCache
```
The entry point is as in `CommonSolve`:
```julia
init(prob::OptimizationProblem, alg, args...; kwargs...)
solve!(cache::AbstractOptimizationCache)
```

Implements init dispatch

---

src/remake.jl
src/solutions/optimization_solutions.jl
test/downstream/Project.toml
test/downstream/remake_autodiff.jl

Fixes https://github.com/SciML/SciMLBase.jl/issues/292

fix autodiff of remake

---

src/utils.jl

This fixes a bug in `NonlinearSolve` and allows us to remove duplicated code from `OrdinaryDiffEq` and `LinearSolve` @YingboMa

add `_unwrap_val` to `SciMLBase`

---

src/interpolation.jl

After solving a DAE I get the following error while processing the solution.
I tried to fix that and tested my changes. My code works now as expected.
```
ERROR: LoadError: UndefVarError: Θm1 not defined
Stacktrace:
[1] interpolant
@ C:\Users\homer\.julia\packages\SciMLBase\cJ8FF\src\interpolation.jl:479 [inlined]
[2] interpolation(tval::Float64, id::SciMLBase.LinearInterpolation{Vector{Float64}, Vector{Vector{Float64}}}, idxs::Int64, deriv::Type{Val{0}}, p::Vector{Any}, continuity::Symbol)
@ SciMLBase C:\Users\homer\.julia\packages\SciMLBase\cJ8FF\src\interpolation.jl:237
[3] (::SciMLBase.LinearInterpolation{Vector{Float64}, Vector{Vector{Float64}}})(tvals::Float64, idxs::Int64, deriv::Type, p::Vector{Any}, continuity::Symbol)
@ SciMLBase …
```

Fixing "UndefVarError: Θm1 not defined"

---

src/remake.jl

In order to be able to move everything related to processing symbolic `p` and `u0` maps to MTK.
- Next step is to implement the interface in MTK:  https://github.com/SciML/ModelingToolkit.jl/pull/1941
- And then to use it instead: https://github.com/SciML/SciMLBase.jl/pull/311

adds process_p_u0_symbolic

---

src/integrator_interface.jl
src/solutions/solution_interface.jl
test/downstream/integrator_indexing.jl
test/downstream/symbol_indexing.jl

Ref. #301 
Indexing is now consistent between indexes and symbols (`sol[1:2, :]` and `sol[[x, y], :]` return the same shape of data) and is type-stable (`sol[(x, y)]` returns a `Vector{Tuple{...}}`)

Consistent indexing with numbers and symbols, improved tests

---

src/integrator_interface.jl
src/solutions/solution_interface.jl
test/solution_interface.jl

Before this PR (reported by @SKopecz):
```julia
julia> using Plots, OrdinaryDiffEq
julia> f = ODEFunction((u, p, t) -> -u, analytic=(u0, p, t) -> u0 * exp(-t))
julia> ode = ODEProblem(f, 1.0, (0.0, 1.0))
julia> sol = solve(ode, Tsit5())
julia> plot(sol, plot_analytic=true)
ERROR: MethodError: no method matching -(::Type{Val{:analytic}})
Closest candidates are:
-(::Any, ::ChainRulesCore.AbstractThunk) at ~/.julia/packages/ChainRulesCore/C73ay/src/tangent_types/thunks.jl:35
-(::Any, ::VectorizationBase.CartesianVIndex) at ~/.julia/packages/VectorizationBase/e4FnQ/src/cartesianvindex.jl:68
-(::Any, ::ChainRulesCore.ZeroTangent) at ~/.julia/packages/ChainRulesCore/C73ay/src/tangent_arithmetic.jl:102
...
Stacktrace:
[1] (::var"#1#3")(u::Type, p::Float64, t::Float64)
@ Main ./REPL[1]:1
[2] …
```

fix plotting of analytic ODE solution

---

src/utils.jl

This has been bugging me for such a long time now that I thought I'd finally go ahead and file a pull request.
Basically, the ANSI color code attempts to mimic the Juno syntax colors but is somewhat off. Using the ANSI format `38;2;R;G;B` it is possible to specify rgb values which better approximate the Juno hex value for types, which is (I believe?) `0x0056b6c2`.

Correct syntax coloring for types

---

src/problems/dae_problems.jl
src/solutions/dae_solutions.jl
src/solutions/solution_interface.jl

This already works for ODEs, but DAEs had some size checks that made this not work. I'll add a downstream test to OrdinaryDiffEq (test needs to be downstream so we can test solving)

allow making and solving DAEs with nothing for u0 and du0

---

src/retcodes.jl

This is the most invalidating one, and it's not actually needed for the conversions.
```julia
julia> Symbol(SciMLBase.ReturnCode.Success)
:Success
```

Remove extra retcode method

---

src/alg_traits.jl

The first half of the file had docstrings starting with "Trait declaration..." while the latter half for the Optimization algorithms was less specific. Also fixed `constrains` to `constraints` in a couple docstrings.

Standardise docstrings for alg traits

---

Project.toml
src/operators/basic_operators.jl

This prepares the ground for https://github.com/JuliaLang/julia/pull/46874. The addition of handling of transpose factorizations seems desirable (and necessary in the above mentioned PR) because real `LU` prefers transpose over adjoints, in contrast to other factorizations.

Prepare for `AdjointFactorization`

---

Project.toml

We don't have a 1.81.1 yet, so decrement version back to that and tag a release? https://github.com/JuliaRegistries/General/blob/master/S/SciMLBase/Versions.toml

Decrement version

---

src/SciMLBase.jl

reexport scimlops now that `issquare` name conflict is fixed in https://github.com/SciML/LinearSolve.jl/pull/270

reexport SciMLOperators

---

src/retcodes.jl

This is one of the top invalidators, we've waited, I don't see issues around this anymore, going for it.

Remove deprecating == conversion of retcode to symbol

---

src/debug.jl
src/problems/problem_utils.jl

Current error message:
```julia
ERROR: MethodError: no method matching *(::Float64, ::SciMLBase.NullParameters)
Some of the types have been truncated in the stacktrace for improved reading. To emit complete information
in the stack trace, evaluate `TruncatedStacktraces.VERBOSE[] = true` and re-run the code.
An arithmetic operation was performed on a NullParameters object. This means no parameters were passed
into the AbstractSciMLProblem (e.x.: ODEProblem) but the parameters object `p` was used in an arithmetic
expression. Two common reasons for this issue are:
1. Forgetting to pass parameters into the problem constructor. For example, `ODEProblem(f,u0,tspan)` should
be `ODEProblem(f,u0,tspan,p)` in order to use parameters.
2. Using the wrong function signature. For example, with …
```

Add error hints on null parameters in missing functions

---

src/integrator_interface.jl

This is useful because it means that if a retcode is set during initialization, it will be checked when calling `solve!`

make check_error return manually set error statuses

---

src/integrator_interface.jl

This will make `EEst = NaN` and `EEst = Inf` problems easier to debug.

More informative error message

---

src/integrator_interface.jl

When combined with https://github.com/SciML/Sundials.jl/pull/401, this allows IDA to be used with `NoInit`. The test for this will be added to the sundials PR once this is merged.

Hook up `NoInit` in scimlBase

---

src/solutions/nonlinear_solutions.jl

This will make it possible for nonlinear solvers to keep track of their statistics which (among other things) will make it so DAE solvers don't skip counting the cost of initialization.

Add NLStats struct for nonlinear solver stat tracking

---

src/performance_warnings.jl

Currently, this will print a warning with every step in the solve, which can be too verbose

Fix Logging Repeatedly

---

src/ensemble/basic_ensemble_solve.jl
src/ensemble/ensemble_problems.jl
test/downstream/ensemble_first_batch.jl
test/downstream/ensemble_multi_prob.jl
test/runtests.jl

This is a fairly simple change that makes it somewhat cleaner to handle the common case where an ensemble is constructed from a list of regular sciml problems.

better support for automatically handling vector ensembles

---

src/ensemble/basic_ensemble_solve.jl
src/ensemble/ensemble_problems.jl
src/ensemble/ensemble_solutions.jl
test/aqua.jl
test/downstream/ensemble_multi_prob.jl

The last test is still failing, but this is almost good to go.
There are also a few typo fixes from https://github.com/SciML/SciMLBase.jl/pull/463 that would have been caught by tests but the tests didn't finish before merging.

make indexing EnsembleSolution work

---

src/ensemble/ensemble_solutions.jl

This allows for easy indexing of an ensemble solution with importance weights. quantiles TODO.

add `WeightedEnsembleSolution`

---

src/ensemble/ensemble_solutions.jl
test/downstream/ensemble_multi_prob.jl

This fixes the indexing issues for Ensembles without the breaking parts of https://github.com/SciML/SciMLBase.jl/pull/466.

fix ensemble indexing

---

src/solutions/solution_interface.jl

This is just a minor fix, when we are plotting a solution **without an analytical solution** but we set ```plot_analytic=true```, the error is weird:

Throw appropriate error when analytic is not given

---

src/interpolation.jl
test/solution_interface.jl

Fixes https://github.com/SciML/SciMLBase.jl/issues/458
Previously the check for whether the interpolation was being asked to extrapolate outside the time range assumed that at least two steps were taken. (otherwise `t[end]-t[1] == 0`).  This would then cause a segfault when you actually try to do the interpolation.

fix segfault when interpolating on failed solution

---

src/interpolation.jl
test/solution_interface.jl

This is a followup to https://github.com/SciML/SciMLBase.jl/pull/476 that fixes some typos and also fixes a bounds error. This also removes unnecessary `@inbounds` that don't improve performance.
Benchmark:
```
julia> using Sundials
julia> mutable struct precflags
prec_used::Bool
psetup_used::Bool
end
julia> prob = DAEProblem(prob_dae_resrob.f, prob_dae_resrob.du0, prob_dae_resrob.u0,
prob_dae_resrob.tspan,  precflags(false, false));
julia> sol = solve(prob, IDA());
#before
julia> @btime sol(85000)
3.474 μs (55 allocations: 4.67 KiB)
julia> @btime sol(1000:1000:90000);
283.921 μs (4776 allocations: 420.81 KiB)
#after
julia> @btime sol(85000)
3.450 μs (55 allocations: 4.67 KiB)
julia> @btime sol(1000:1000:90000);
284.034 μs (4776 allocations: 420.81 KiB)
```

fix vector interpolation and remove unnecessary `@inbounds`

---

src/scimlfunctions.jl

https://github.com/SciML/DiffEqDocs.jl/issues/688

Change f to f1 in SplitFunction docs

---

src/SciMLBase.jl
src/problems/basic_problems.jl
test/function_building_error_messages.jl

See [this issue](https://github.com/SciML/Integrals.jl/pull/173).

Add `DataIntegralProblem`

---

src/problems/basic_problems.jl

I found a way to make this Val type unnecessary. This makes the code simpler, type stable, and more performant for small problems.

remove Value type requirement from SampledIntegralProblem

---

src/problems/ode_problems.jl

Adds a big warning not to use it. This is only for EnzymeRules to work given current limitations!!!

Make ODEProblem into a mutable struct, v2

---

src/problems/ode_problems.jl

Required for use in a reverse-mode EnzymeRule. Otherwise there is a mixed activity for having both floats and vector{floats}, not behind a pointer.

Make ODEProblem into a mutable struct

---

Project.toml
src/problems/sde_problems.jl

Tested locally, this patch may fix all the issues

Fix SDEProblem constructor issues

---

src/problems/basic_problems.jl

Needed to fix Optimization doc build.

fix OptimizationFunction refs

---

src/problems/basic_problems.jl

I have no clue which ones need to be displayed. I am just unbreaking the precompilation

[URGENT] Unbreak Precompilation of SciMLBase on 1.9 with TruncatedStacktraces enabled!

---

Project.toml
src/problems/bvp_problems.jl
src/remake.jl
src/scimlfunctions.jl

Make construction of type stable TP BVProblem easier

---

.gitignore
Project.toml
ext/PythonCallExt.jl
src/problems/analytical_problems.jl
src/problems/bvp_problems.jl
src/problems/dae_problems.jl
src/problems/dde_problems.jl
src/problems/discrete_problems.jl
src/problems/implicit_discrete_problems.jl
src/problems/ode_problems.jl
src/problems/rode_problems.jl
src/problems/sdde_problems.jl
src/problems/sde_problems.jl
src/problems/steady_state_problems.jl
src/scimlfunctions.jl
src/utils.jl
test/python/Project.toml
test/python/pythoncall.jl
test/runtests.jl

The goal of this PR is to make PythonCall and the DifferentialEquations ecosystem fully compatible, making https://github.com/SciML/diffeqpy/pull/118 trivial.
I think I've implemented the nontrivial design decisions that have to be made, so this is ready for review. If the design looks good and once #502 merges, I'll finish the details to get this to a mergeable state.

Add PythonCall Extension

---

Project.toml
ext/SciMLBasePyCallExt.jl
ext/SciMLBasePythonCallExt.jl
ext/SciMLBaseRCallExt.jl
ext/SciMLBaseZygoteExt.jl

Fixes the name of the extensions so they don't clash elsewhere. Also adds an RCall one which is basic and assumes out of place, which is a fine assumption given that R is copy-on-write and thus mutation of the form of an in-place function is just not possible. This means that we don't get the great error messages, but oh well we can figure that out later.
Fixes https://github.com/SciML/diffeqr/issues/41
Better version requires https://github.com/JuliaInterop/RCall.jl/issues/503

Rename the extension packages and do RCall as well

---

Project.toml
src/SciMLBase.jl
src/problems/basic_problems.jl
src/remake.jl

Add NonlinearLeastSquaresProblem

---

src/problems/basic_problems.jl
src/problems/steady_state_problems.jl
test/convert_tests.jl

This PR fixes [this issue](https://github.com/SciML/NonlinearSolve.jl/issues/204#issue-1887560838) @ChrisRackauckas @avik-pal

kwargs are passed when converting ODEProblem to SteadyStateProblem and NonlinearProblem

---

ext/SciMLBasePythonCallExt.jl
test/python/pythoncall.jl

Fixes the problem reported in https://github.com/SciML/diffeqpy/issues/111#issuecomment-1772859284

Promote initial state when converting from non-homogeneous python lists.

---

src/utils.jl
test/function_building_error_messages.jl

Fixes https://github.com/SciML/SciMLBase.jl/issues/529

fix and test handling of UnionAll in isinplace checks

---

src/problems/basic_problems.jl
src/scimlfunctions.jl

This pr is needed by Integrals.jl so that the new interface introduced in SciMLBasev2 can correctly reproduce the old behavior. Mainly, the documentation now says that the integrand prototypes are arrays of the same kind as what the integrand will consume, and integral algorithms are responsible for providing those same arrays.
The only additional thing I added were `getproperty` methods for the bounds of the integration domain. Although these will no longer be used by the updated Integrals.jl, it could help avoid bugs for users migrating to the new version.

BatchIntegralFunction revisions

---

src/problems/basic_problems.jl
test/downstream/nllsopt.jl

Fixes https://github.com/SciML/Optimization.jl/issues/622

 Add constructor to convert NLLS to OptimizationProblem

---

Project.toml
src/ensemble/basic_ensemble_solve.jl

This is the first part of a series of PRs that adds progress support to EnsemblePoblem.
What this part does is if progress is enabled, initialize progress bars for every trajectory, and give every solve an unique ID.
For very large ensembles the expectation is that the logger shows this in a sensible way, for example, show the overall progress:
```
sum_logger = let progress = Dict{Symbol, Float64}()
TransformerLogger(TerminalLogger()) do log
if log.level == LogLevel(-1) && haskey(log.kwargs, :progress)
@show log
pr = log.kwargs[:progress]
if pr isa Number
progress[log.id] = pr
elseif pr == "done"
progress[log.id] = 1.0
end
tot = sum(values(progress))/length(progress)
if tot>=1.0
tot="done"
empty!(progress)
end
log = merge(log, (;id=:total, message="Total", kwargs=Dict(:progress=>tot))) …
```

progress bars for EnsembleProblem

---

Project.toml
src/solutions/nonlinear_solutions.jl

See https://github.com/SciML/NonlinearSolve.jl/pull/292

Allow storing a trace object in NonlinearSolution

---

ext/SciMLBaseZygoteExt.jl

fix: bugs relating to RecursiveArrayTools@3

---

src/symbolic_utils.jl

fix: add cleansyms method to hotfix plotting

---

Project.toml
src/problems/basic_problems.jl
src/scimlfunctions.jl

Fix docstring refrences optfun and optprob

---

src/solutions/solution_interface.jl

fix: use pdesystem for AbstractPDESolution SII

---

Project.toml
src/problems/basic_problems.jl

Fixes https://github.com/SciML/NonlinearSolve.jl/issues/168

Throw an error if p is supplied as kwarg

---

src/problems/steady_state_problems.jl

Fixes https://github.com/SciML/NonlinearSolve.jl/issues/221

Remove non-existing ref for NonlinearSolve docs

---

src/integrator_interface.jl
src/solutions/solution_interface.jl
src/symbolic_utils.jl
test/solution_interface.jl

Fixes a whole lot of small issues.

Change the plot recipes to use the SymbolicIndexingInterface

---

src/problems/basic_problems.jl
test/performance_warnings.jl

Fixes https://github.com/SciML/Integrals.jl/issues/198
Fixes https://github.com/SciML/Integrals.jl/issues/208
Specifically, this pr deprecates the following method:
```julia
@deprecate IntegralProblem(f::AbstractIntegralFunction,
lb::Union{Number,AbstractVector{<:Number}},
ub::Union{Number,AbstractVector{<:Number}},
p = NullParameters(); kwargs...) IntegralProblem(f, (lb, ub), p; kwargs...)
```
@ChrisRackauckas this pr could also be a good time to decide on the promotion behavior for the endpoints of the integration domain. I actually think promotion should be handled at solve time since it could interfere with AD, e.g. using ForwardDiff and differentiating just the upper limit of integration.
[contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in …

Deprecate separate lb, ub arguments to IntegralProblem

---

src/solutions/solution_interface.jl
test/solution_interface.jl

This allows the user to specify the times to plot at when using the recipe. This makes it so you can better control the times even when just using the automated dense form. This is much better than interpolating and then plotting since it has all of the niceties like the automated labels.

Implement plotat for solution plot recipe

---

src/solutions/optimization_solutions.jl

Related to https://github.com/SciML/Optimization.jl/pull/652

Remove solve_time since that'll be in stats

---

src/solve.jl

Update solve docstring with new callback syntax

---

src/ensemble/ensemble_analysis.jl
src/ensemble/ensemble_solutions.jl

The pot recipes for ensemble still use linear indexing in some places. I've updated the places where I saw warnings from, but I'm not sure if I haven't missed something.

update ensemble indexing in the plot recipe

---

src/ensemble/ensemble_solutions.jl

I missed this ones.
@AayushSabharwal is this ok? It seems a bit odd to need `sim.u.u[1]` at first sight.

fix deprecated indexing in EnsembleSummary plot recipe

---

src/remake.jl
src/scimlfunctions.jl
src/solutions/optimization_solutions.jl
src/solutions/solution_interface.jl
test/downstream/Project.toml
test/downstream/integrator_indexing.jl
test/downstream/remake_autodiff.jl
test/downstream/solution_interface.jl
test/downstream/symbol_indexing.jl

Contrary to the name of the branch, this PR should be able to be merged without MTKv9

fix: remove implicit MTK dependency, other bug fixes, MTKv9 compatibility

---

src/solutions/ode_solutions.jl

Required to make https://github.com/SciML/SciMLSensitivity.jl/pull/905#issuecomment-1732334963 work.

make sensitivity_solution work with Enzyme

---

src/solutions/solution_interface.jl

refactor: implement two-argument SII.parameter_values

---

src/problems/basic_problems.jl
src/scimlfunctions.jl
test/function_building_error_messages.jl

The updates to `IntegralProblem`s in SciML v2 lost the ability to set an in-place `IntegralProblem` for a non-`IntegralFunction`, observed here https://github.com/SciML/SciMLExpectations.jl/pull/148, and inadequate web documentation for the new interface, as in this issue https://github.com/SciML/Integrals.jl/issues/218 and a [discourse post](https://discourse.julialang.org/t/is-there-any-documentation-on-integralfunctions/108970/9). I want to address the following in this pr
I would appreciate comments on my writing and how we should publish the docstrings. I will also open a pr …

[RFC] Better integral docs

---

src/solutions/dae_solutions.jl

This adds the `k` field to `DAESolution` which will allow for a future PR to OrdinaryDiffEq to make DAEs save their k's which is necessary to interpolate their solutions.

Prepare `DAESolution` for interpolation

---

src/callbacks.jl
test/python/pythoncall.jl

Fixes https://github.com/SciML/diffeqpy/issues/136.

prepare condition functions

---

Project.toml
src/integrator_interface.jl

When set to false allows the integrator to skip recalculating the interpolation data. This is a prereq to https://github.com/SciML/OrdinaryDiffEq.jl/pull/2141 being finished.

add optional `continuous_modification` argument to `reeval_internals_due_to_modification!`

---

src/problems/problem_interface.jl

fix: properly implement SII fallbacks for AbstractJumpProblem

---

src/solutions/ode_solutions.jl

This includes the fields  in DEstats
nfpiter::Int 
nfpconvfail::Int 
from DDE
there is a PR in DDE.jl which utilises this change to allow for parallel execution of DDE

Update stats field

---

src/scimlfunctions.jl
test/function_building_error_messages.jl

Previously, `IntegralFunction(f, integrand_prototype)` would error for oop `f` and this pr makes it possible to pass an oop `f` because the `integrand_prototype` is still useful to infer the return type of `f` without evaluating it. Integral algorithms often need to have a prototype to have a correct wrapper so this will avoid additional integrand evaluations.

allow `integrand_prototype` for oop integral functions

---

src/alg_traits.jl

Added trait for checking derivative requirement #711

Added trait for checking derivative requirement #711

---

src/solutions/optimization_solutions.jl

`DEStats` are nicely presented in the REPL. This PR implements the same functionality for `OptimizationStats`.

Implement a `Base.show` for `OptimizationStats`

---

Project.toml
src/solutions/solution_interface.jl
test/downstream/solution_interface.jl

Fixes https://github.com/SciML/OrdinaryDiffEq.jl/issues/2162
The changes of this part of the code were introduced in https://github.com/SciML/SciMLBase.jl/pull/572/files
I also added some real (smoke) tests for this, including loading Plots.jl and generating some plots (maybe unicodeplots?).
It would be nice to get a new release including this fix.

fix plotting analytic time series

---

src/SciMLBase.jl
src/problems/bvp_problems.jl
src/remake.jl
src/scimlfunctions.jl
src/solutions/ode_solutions.jl
test/downstream/modelingtoolkit_remake.jl
test/remake_tests.jl
test/traits.jl

The main compilation cost for BVDiffEq is coming from solving NLLS problems. Having this allows us to have a type stable path for NLLS BVPs.

Add a nlls trait to BVProblem

---

src/integrator_interface.jl
test/downstream/integrator_indexing.jl

fix: fix `setindex!` not erroring appropriately for integrators

---

docs/src/interfaces/Problems.md
src/remake.jl
test/remake_tests.jl

 fix: fix remake initialization with dependent default values

---

src/solutions/rode_solutions.jl
test/downstream/solution_interface.jl

fix: fix symbolic idxs interpolation for RODESolution

---

src/problems/bvp_problems.jl
src/scimlfunctions.jl
test/function_building_error_messages.jl

Add jvp and vjp fields to OptimizationFunction

---

src/solve.jl

Changed trait constraints to solve.jl for calculation of gradients, hessians and more. #651

---

Project.toml
src/SciMLBase.jl
src/problems/bvp_problems.jl

Similar to `TwoPointBVProblem`, this PR adds the `TwoPointSecondOrderBVProblem` constructor.

Add TwoPointSecondOrderBVProblem constructor

---

src/integrator_interface.jl
test/integrator_tests.jl

Fixes #669.
I'm not sure why this check was there. Was it just to save work? Why should the postamble not run if it is successful?

Remove check in `check_error!`

---

src/problems/basic_problems.jl

This doesn't change anything yet, but is a step in the direction of making NonlinearSolve not specialize on the user given function which will reduce compilation time on first nonlinear solve.

autospecialize rather than full specialize by default for the various `NonlinearProblems`

---

ext/SciMLBaseChainRulesCoreExt.jl
ext/SciMLBaseZygoteExt.jl
test/downstream/symbol_indexing.jl

Before this PR, indexing with vector of symbols fails at the check for symbolic variables at https://github.com/SciML/SciMLBase.jl/blob/9d87ca04a15f6f94a2f3362f91a95a66950003ae/ext/SciMLBaseZygoteExt.jl#L111
and returns 
```julia
@parameters σ ρ β
@variables x(t) y(t) z(t) w(t)
eqs = [D(D(x)) ~ σ * (y - x),
D(y) ~ x * (ρ - z) - y,
D(z) ~ x * y - β * z,
w ~ x + y + z]
@mtkbuild sys = ODESystem(eqs, t)
u0 = [D(x) => 2.0,
x => 1.0,
y => 0.0,
z => 0.0]
p = [σ => 28.0,
ρ => 10.0,
β => 8 / 3]
tspan = (0.0, 100.0)
prob = ODEProblem(sys, u0, tspan, p, jac = true)
sol = solve(prob, …
```

fix: Correct gradients for vector of symbols while indexing

---

ext/SciMLBaseChainRulesCoreExt.jl
ext/SciMLBaseZygoteExt.jl

`SDESolution` doesn't seem to exist anymore. The more appropriate type seems to be `RODESolution`. This PR removes mentions of SDESolution and replaces them with `RODESolution`. Further, one of the adjoints was incorrect. It was definining an adjoint over SDEProblem, but instead tries returning SDESolution in the forwards pass. Not sure how this passed tests though

chore: Remove mentions of SDESolution

---

src/solutions/ode_solutions.jl
test/downstream/symbol_indexing.jl

Close https://github.com/SciML/ModelingToolkit.jl/issues/2697

fix: error when interpolating derivatives of observed variables

---

src/ensemble/ensemble_solutions.jl

fix: don't rely on RAT internals in EnsembleSolution indexing

---

src/integrator_interface.jl

Previously, we would run the instability check no matter how badly the integrator had controlled the error. This caused issues, especially for the first timestep where the dt chosen was fairly arbitrary. We could end up in a situation very easily where the first timestep was big enough that the step would result in incredibly large (or NaN) u values. This step would get rejected, but because the values were incorrectly really big, we would get killed by instability detection. This is silly because just shrinking the `dt` would have made it stable, but we didn't get a chance to do so.
```
function rober(du, u, p, t)
y₁, y₂, y₃ = u
k₁, k₂, k₃ = p
du .= [-k₁ * y₁ + k₃ * y₂ * y₃,
k₁ * y₁ - k₃ * y₂ * y₃ - k₂ * y₂^2,
k₂ * y₂^2]
end
prob = ODEProblem(rober, …
```

only bail out as instable when dt is small or error is somewhat conrtolled

---

src/solutions/ode_solutions.jl

This was likely just a copy paste bug. Since it's an estimate, and the main thing we care about is whether it's .5 or 1e20 it's very silly to print this value as an int.

print maxeig as a float

---

src/integrator_interface.jl

Followup to https://github.com/SciML/SciMLBase.jl/pull/692. It turns out that OrdinaryDiffEq sets the minimum dt to `eps(t)` which is relatively sensible, but that means that we should be failing with an error if we don't accept a step and we're already at the minimum dt.
This definitely needs some tests, but I think those tests need to be in OrdinaryDiffEq so they will be added as a separate PR once this merges.

improve dtmin and unstable detection

---

ext/SciMLBaseMakieExt.jl
src/ensemble/ensemble_solutions.jl

- Updated the `trajectories` kwarg to `idxs` in the `EnsembleSummary` recipes for both `Plots` and `Makie`. 
- Should now allow users to select which variables to show summary line series of, in line with what the documentation shows. 
- Wasn't sure where to put tests for this, or where plotting tests are kept. Should be something like:
```julia
idxs = (2, 3)
ensemble_summary_plot = plot(ensemble_summary; idxs)
@test ensemble_summary_plot.n == length(idxs)
``` 
1. Was the original intention of the `EnsembleSummary` recipes to allow users to choose/truncate the amount of trajectories that statistics are plotted over, similar to `EnsembleSimulation`? (Explains the mixup with `idxs`)
- If so, that functionality is missing and should be added
2. Symbolic indexing does not work any of the …

Fix `EnsembleSummary` plot recipe kwarg #697 

---

ext/SciMLBaseZygoteExt.jl

Now that https://github.com/SciML/SciMLSensitivity.jl/pull/1056 has been merged, this adjoint can be removed from here.

Remove `literal_getproperty` adjoint from SciMLBase

---

src/remake.jl
test/downstream/modelingtoolkit_remake.jl

fix: fix `u0` dependent on `p` not working with `remake`

---

ext/SciMLBaseZygoteExt.jl
test/downstream/modelingtoolkit_remake.jl

test: fix several downstream test failures

---

src/integrator_interface.jl

See https://discourse.julialang.org/t/how-to-decipher-scimlbase-optimizationbase-optimizationforwarddiffext-warnings/115225 for motivation. I'm still not fully happy with this but I do think it's an improvement.

improve Unstable error message

---

src/remake.jl
test/remake_tests.jl

fix: handle edge case when `()` as parameters triggers error

---

src/problems/bvp_problems.jl
src/scimlfunctions.jl

Previous ```SecondOrderBVProblem``` always set ```problem_type``` as ```nothing```. This PR fixes this issue.

Fix twopoint Val for SecondOrderBVProblem

---

src/remake.jl
test/remake_tests.jl

fix: fix remake for `IntervalNonlinearProblem`

---

docs/src/interfaces/Init_Solve.md
docs/src/interfaces/Problems.md
docs/src/interfaces/SciMLFunctions.md
src/SciMLBase.jl
src/alg_traits.jl
src/debug.jl
src/integrator_interface.jl
src/operators/diffeq_operator.jl
src/problems/problem_utils.jl
src/retcodes.jl
src/scimlfunctions.jl

(none necessary, only documentation changed)
Main changes
- Identify method headers in docstrings (indents)
- Use of backticks/monospace in names relating to code (and markdown deals with underscores as italics)
- Fix markdown lists

Documentation fixes

---

src/remake.jl

A "proper" fix for this would be making it so https://github.com/SciML/SciMLBase.jl/blob/9978e5bf498badac05ff4db606322fa9bf9dffc7/src/scimlfunctions.jl#L4378-L4381 didn't always do `FullSpecialize` but changing that is breaking.

fix: fix `remake` changing specialization of `ODEFunction`

---

src/ensemble/ensemble_solutions.jl

fix: fix indexing in `calculate_ensemble_errors`

---

.github/workflows/Downstream.yml

I'm not sure I've done this right, but I'd like to propose adding Catalyst as a downstream test. We have very comprehensive tests with V14, including for all kinds of symbolic indexing and plotting courtesy of @TorkelE, and I think some of the issues with stuff inadvertently getting broken might get caught if Catalyst was tested on such PRs to SciMLBase (and MTK, but Catalyst is already downstream there). It would also be very helpful to us in trying to diagnose sudden Catalyst breakages to be able to see if it had already broken in a merged SciMLBase PR.

Add Catalyst as a downstream test

---

src/solutions/solution_interface.jl

This allows JumpProcesses to dispatch this function for SSAStepper, and hence get piecewise linear plotting when not saving every jump.

factor denseplot kwarg calculation to function

---

src/ensemble/ensemble_solutions.jl

- Single integer `getindex` should fallback to RAT and depwarn
- Double integer `getindex` is defined
- 3+ integer `getindex` is what the last method is intended to be, but is implemented wrong for two reasons
- `idxs` needs to be splatted, since otherwise it passes a `Tuple` to `getindex`
- It should specifically require 3+ integers to avoid ambiguities

fix: fix ambiguity in AbstractEnsembleSolution indexing

---

src/SciMLBase.jl
src/problems/optimization_problems.jl
src/scimlfunctions.jl
src/solve.jl

Added struct and constructors, updated OptimizationProblem for MOO

---

src/alg_traits.jl
src/interpolation.jl
src/utils.jl

Raises `has_lazy_interpolation` trait to SciMLBase.
Introduces `strip_interpolation` function to strip functions from interpolation objects, to accommodate serialization better.

Lazy interpolation trait, stripping interpolation

---

src/remake.jl
test/remake_tests.jl

fix remake when args is a field of the struct

---

src/solutions/ode_solutions.jl

- [x ] Appropriate tests were added
- [x ] Any code changes were done in a way that does not break public API
- [x ] All documentation related to code changes were updated
- [x ] The new code follows the
- [x ] Any new documentation only uses public API
Changes `strip_solution` to use a custom exception type.

use custom exception for lazy interpolation

---

src/SciMLBase.jl
src/alg_traits.jl

Came from https://github.com/SciML/StochasticDiffEq.jl/pull/583

add `AlgorithmInterpretation`

---

src/alg_traits.jl
src/utils.jl
test/function_building_error_messages.jl

This helps us at https://github.com/SKopecz/PositiveIntegrators.jl

allow different number of out-of-place args for isinplace

---

src/alg_traits.jl

To add errors/warning that additive alg do not work with correlated or non-diagonal sde problems
https://github.com/SciML/StochasticDiffEq.jl/issues/581
https://github.com/SciML/StochasticDiffEq.jl/issues/578

add additative noise trait

---

src/remake.jl
test/remake_tests.jl

fix: fix `remake` handling identical variables with different names

---

Project.toml
src/problems/optimization_problems.jl
src/scimlfunctions.jl

Update docstrings for Optimization v4

---

Project.toml
src/solutions/ode_solutions.jl
test/downstream/ode_stripping.jl

- [x ] Appropriate tests were added
- [x ] Any code changes were done in a way that does not break public API
- [x ] All documentation related to code changes were updated
- [x ] The new code follows the
- [x ] Any new documentation only uses public API
Fixes interpolation for stripped solution objects, i.e. solution objects from `strip_solution`.
I'm not sure about doing `struct ODENullFunction <: SciMLBase.AbstractODEFunction{false} end`, but the inner constructor for ODEProblem doesn't allow `f` to be nothing. And the alternative seems to be changing the functors for …

Fix interpolation for stripped solutions

---

Project.toml
src/remake.jl
test/downstream/modelingtoolkit_remake.jl
test/traits.jl

fix: support remake with array symbolic whose index is an array of indices

---

src/problems/ode_problems.jl
src/remake.jl
src/scimlfunctions.jl

feat: support `initializeprobpmap` in relevant `SciMLFunctions`

---

src/solutions/ode_solutions.jl
test/solution_interface.jl

Close https://github.com/SciML/RecursiveArrayTools.jl/issues/396

fix: handle empty `idxs` in interpolation

---

src/scimlfunctions.jl

A few minor improvements to https://github.com/SciML/SciMLBase.jl/pull/816

SplitFunction W_prototype fixes

---

src/SciMLBase.jl
src/integrator_interface.jl
src/scimlfunctions.jl
src/solutions/dae_solutions.jl
src/solutions/ode_solutions.jl
src/solutions/rode_solutions.jl
src/solutions/save_idxs.jl
src/solutions/solution_interface.jl
test/downstream/solution_interface.jl

feat: support symbolic indexing of a subset of the system

---

src/remake.jl
test/downstream/modelingtoolkit_remake.jl

@isaacsas @TorkelE this should fix the `remake` issue you were having with conservation laws.

fix: fix `remake` for parameters dependent on observed variables

---

Project.toml
src/remake.jl
test/downstream/modelingtoolkit_remake.jl
test/downstream/solution_interface.jl
test/remake_tests.jl

fix: fix remake with u0 dependent on `Symbol` parameter

---

src/solutions/save_idxs.jl
test/downstream/solution_interface.jl

This helps avoid duplicating code when adding symbolic save_idxs to solver libraries

feat: add `get_save_idxs_and_saved_subsystem`

---

src/integrator_interface.jl

Add reinitialization argument for change_t_via_interpolation for pre-affect reinitialization

---

src/remake.jl
src/solutions/solution_interface.jl
test/downstream/modelingtoolkit_remake.jl

feat: add cycle detection in initial conditions

---

src/SciMLBase.jl
src/problems/nonlinear_problems.jl
src/solutions/nonlinear_solutions.jl

Creates a runtime description of an SCC-split nonlinear system to allow for specializing the solve of nonlinear problems which are splittable.

Add SCCNonlinearProblem

---

.github/workflows/Downstream.yml
src/ODE_nlsolve.jl
src/SciMLBase.jl
src/initialization.jl
src/scimlfunctions.jl
test/downstream/initialization.jl
test/initialization.jl
test/runtests.jl

This replaces `default_nlsolve` in OrdinaryDiffEq, and will have methods in NonlinearSolve which can then be leveraged by all libraries for initialization.

feat: add fields to `OverrideInit`, better `nlsolve_alg` handling 

---

src/remake.jl
test/downstream/adjoints.jl

Required for https://github.com/SciML/ModelingToolkit.jl/pull/3226.

refactor: change `remake_initialization_data`

---

src/problems/nonlinear_problems.jl
src/problems/problem_utils.jl
test/downstream/problem_interface.jl

feat: implement SII for `SCCNonlinearProblem`

---

src/initialization.jl
src/problems/nonlinear_problems.jl

feat: allow SCCNonlinearProblem in OverrideInit

---

src/initialization.jl
src/problems/nonlinear_problems.jl
test/initialization.jl

fix: handle `I` as mass matrix for `CheckInit`

---

src/scimlfunctions.jl

There are some places in the file where ArrayInterfaceCore is used, but this errors since it's not in the SciMLBase dependencies

switch ArrayInterfaceCore to ArrayInterface in some places

---

src/remake.jl
test/downstream/modelingtoolkit_remake.jl

feat: add `remake` for `SCCNonlinearProblem`

---

src/problems/nonlinear_problems.jl
src/remake.jl
test/downstream/modelingtoolkit_remake.jl
test/downstream/problem_interface.jl

refactor: change `SCCNonlinearProblem` fields

---

src/SciMLBase.jl
src/initialization.jl

Follows on from https://github.com/SciML/OrdinaryDiffEq.jl/issues/2513 and https://github.com/SciML/OrdinaryDiffEq.jl/pull/2514 .
This pull request exports `CheckInit` and adds an informative error message for `CheckInit` if supplied initialization isn't incorrect, as discussed in the above pull request.
As far as SciMLBase is concerned, I don't believe this should be breaking in any way. This is required before merging https://github.com/SciML/OrdinaryDiffEq.jl/pull/2514 .

Make CheckInit more informative

---

src/initialization.jl
src/remake.jl
test/downstream/modelingtoolkit_remake.jl
test/initialization.jl

feat: add lazy initialization to `remake`

---

src/remake.jl
test/downstream/problem_interface.jl

fix: check if `prob.f.sys` exists before accessing it in `remake`

---

docs/src/interfaces/Common_Keywords.md
src/SciMLBase.jl
src/problems/analytical_problems.jl
src/problems/bvp_problems.jl
src/problems/dae_problems.jl
src/problems/dde_problems.jl
src/problems/discrete_problems.jl
src/problems/implicit_discrete_problems.jl
src/problems/integral_problems.jl
src/problems/linear_problems.jl
src/problems/nonlinear_problems.jl
src/problems/ode_problems.jl
src/problems/optimization_problems.jl
src/problems/rode_problems.jl
src/problems/sdde_problems.jl
src/problems/sde_problems.jl
src/problems/steady_state_problems.jl

- [ x] Appropriate tests were added
- [ x] Any code changes were done in a way that does not break public API
- [ x] All documentation related to code changes were updated
- [ x] The new code follows the
- [ x] Any new documentation only uses public API
This adds the abstract type `AbstractAliasSpecifier` and the concrete subtypes `ODEAliases` and `LinearAliases` meant to hold information on which variables to alias when solving the problems. When an alias specifier is true, that variable is aliased, and vice versa for false. When the alias specifier is `nothing`, the solvers …

Add aliasing API types

---

src/SciMLBase.jl
src/initialization.jl
src/remake.jl
src/scimlfunctions.jl
test/remake_tests.jl

feat: add new `remake(::AbstractSciMLFunction)`, fix some `remake` bugs.

---

src/problems/nonlinear_problems.jl
test/problem_building_test.jl

fix: fix `constructorof` for `NonlinearLeastSquaresProblem`

---

src/problems/linear_problems.jl

Fix the LinearAliasSpecifier constructor

---

src/SciMLBase.jl
src/scimlfunctions.jl
test/downstream/comprehensive_indexing.jl

feat: add `HomotopyContinuationProblem`

---

src/scimlfunctions.jl

fix: several `HomotopyNonlinearFunction` fixes

---

src/problems/rode_problems.jl
src/problems/sdde_problems.jl
src/problems/sde_problems.jl

SDE, SDDE, RODE problems can choose to alias the jump process when they're wrapped in a JumpProblem, so a kwarg is needed. 
Additionally, RODE problems can choose to alias the noise problem, so that needed to be added as well.

Add arguments for alias_noise and alias_jumps for RODEs, SDEs, SDDEs

---

src/remake.jl
test/downstream/modelingtoolkit_remake.jl

It looks like the `explicitfuns!` argument is directly forwarded to the constructor resulting in broken problems after a remake due to `explicitfuns!` being `missing`.

Fix `remake` for `SCCNonlinearProblem`

---

src/initialization.jl
test/initialization.jl

feat: allow `initializeprobmap` to be `nothing`

---

src/solutions/ode_solutions.jl

Fixes 
```
┌ Error: Cannot resolve @ref for md"[`SavedSubsystem`](@ref)" in src/types/ode_types.md.
│ - No docstring found in doc for binding `SciMLBase.SavedSubsystem`.
│ - No docstring found in doc for binding `Main.SavedSubsystem`.
└ @ Documenter ~/.cache/julia-buildkite-plugin/depots/0185fce3-4489-413a-a934-123dd653ef61/packages/Documenter/Bs999/src/utilities/utilities.jl:44
```

Reference SavedSubsystem in docs

---

src/initialization.jl
test/initialization.jl

feat: support `NoInit` in `get_initial_values`

---

src/remake.jl
test/downstream/modelingtoolkit_remake.jl

fix: handle `:var => nothing` provided to `remake`

---

src/remake.jl
test/downstream/modelingtoolkit_remake.jl

Looks like `prob.f.sys` was dropped too.

fix: make sure remake(::SCCNonlinearProblem) doesn't drop prob.f.sys

---

src/problems/problem_utils.jl
src/remake.jl
test/initialization.jl
test/remake_tests.jl

fix: fix eager initialization in `remake`

---

src/clock.jl

The Expronicon singleton variant is `Continuous`, for Moshi it is `Continuous()`. This makes `Continuous()` return `Continuous` so we can update ModelingToolkit to the new syntax already.
The actual migration PR is #922, but this should go first unless you the direct route as mentioned in that PR.

Allow future Moshi style syntax to ease transition

---

src/remake.jl
src/scimlfunctions.jl
test/remake_tests.jl

fix: fix `remake(::HomotopyNonlinearFunction)`

---

src/remake.jl
test/remake_tests.jl

Required for https://github.com/SciML/ModelingToolkit.jl/pull/3347

feat: add `late_binding_update_u0_p`

---

Project.toml
src/remake.jl

This is the piece of code that's assuming _func_cache doesn't match cache which now that the names are complete we don't need to sidestep the common path.

Remove SplitFunction remake drop

---

src/initialization.jl
src/problems/problem_utils.jl

Towards https://github.com/SciML/ModelingToolkit.jl/issues/3268

Showing initialization information for `AbstractDEProblem`

---

src/initialization.jl
src/problems/problem_utils.jl
test/downstream/initialization.jl

Should be actually working now, tested on some ModelingToolkit cases

Fix summary errors

---

src/initialization.jl
test/initialization.jl

The previous implementation would fail when `iprob.u0 === nothing`, or if `iprob.f` is a purely inplace function, or if `iprob.f` returned `nothing`.

fix: fix and test `initialization_status`

---

src/clock.jl
test/clock.jl

Tentative to fix: https://github.com/SciML/SciMLBase.jl/issues/945

Fix: make isclock robust to non TimeDomain argument

---

src/clock.jl
test/clock.jl

Fixes #945
Reported upstream as https://github.com/Roger-luo/Moshi.jl/issues/43.
This should restore the old behavior. One possible exception is `is_discrete_time_domain`, which was defined as not being continuous. So that previously returned true for non-clocks, which seems undesirable to me. Though I'd be happy to preserve that behavior if it is expected anywhere.

Support Moshi wildcards via dispatch

---

src/initialization.jl
test/initialization.jl

feat: forward kwargs to `solve` in `OverrideInit`

---

src/remake.jl

Fix _func_cache type promotion in remake

---

ext/SciMLBaseZygoteExt.jl

There are some cases where `.u` becomes scalar. Could be when `u0` is a float or `save_idxs` is a Integer for example. This shows up in SciMLSensitivity https://github.com/SciML/SciMLSensitivity.jl/actions/runs/14307459224/job/40094466372?pr=1168#step:6:1036

HOTFIX: handle `getindex` adjoint for scalar `u`

---

ext/SciMLBaseZygoteExt.jl

Adds a pass-through adjoint for `remake(::ODEFunction)` to resolve some of the failures in https://github.com/SciML/SciMLSensitivity.jl/actions/runs/14308490679/job/40121723763?pr=1168

chore: add remake adjoint for `ODEFunction`

---

src/remake.jl

fix: allow `build_initializeprob` to be a `Bool` in `remake`

---

src/SciMLBase.jl
src/interpolation.jl
src/problems/implicit_discrete_problems.jl
src/scimlfunctions.jl

For the optimal control interface. Have not added the ControlProblem type yet (since these are being implemented in MTK extensions for now.)

feaet: add ControlFunction

---

.github/workflows/Downstream.yml

https://github.com/SciML/SciMLSensitivity.jl/pull/1189 highlights that the downstream tests that are failing for SciMLSensitivity.jl are actually Enzyme issues with v1.11. These are now being tracked here https://github.com/EnzymeAD/Enzyme.jl/issues/2318 for the Enzyme developers to work on. But there are certain things we've been weary about, like:
* https://github.com/SciML/SciMLBase.jl/pull/997
* https://github.com/SciML/SciMLBase.jl/pull/998
Because of failing downstream tests. But that's counter productive: we're not improving our autodiff interfaces because we see failures, but those aren't failures of our autodiff interfaces, those are Enzyme failures.
So for now the solution seems to be to go to v1.10 in these downstream tests and increase the coverage of SciMLSensitivity, and …

Improve Downstream testing

---

ext/SciMLBaseZygoteExt.jl

Solves https://github.com/SciML/SciMLSensitivity.jl/actions/runs/14630001687/job/41063831799?pr=1168

Remove `literal_adjoint(::NoTimeSolution)`

---

Project.toml
ext/SciMLBaseChainRulesCoreExt.jl

These ones are only hit in the DiffEqGPU interfaces right now. Although we will shortly switch to Tangent projections soon, this will at least get tests working there again for now.

Update some solution adjoint reverse mode rules

---

src/ensemble/basic_ensemble_solve.jl
src/ensemble/ensemble_problems.jl

fix: fix depwarn in `EnsembleProblem` constructor

---

src/ensemble/ensemble_problems.jl

I have improved the comments and documentation for the EnsembleProblem to provide a clearer explanation of its constructors and functions.

Ensemble doc fix

---

src/solve.jl

Fixes https://github.com/SciML/Optimization.jl/issues/885

Add a better error message for non-concrete eltypes

---

src/problems/optimization_problems.jl
src/scimlfunctions.jl
test/aqua.jl
test/function_building_error_messages.jl

pulled out the uncontroversial part from https://github.com/SciML/SciMLBase.jl/pull/1019

fix function inference

---

src/initialization.jl

https://github.com/SciML/ModelingToolkit.jl/pull/3585#issuecomment-2883919162

refactor: rewrite `OverrideInit` to be more Zygote compatible

---

src/initialization.jl
src/utils.jl

`nlsol` has 2 incompatible graphs that assign to the same variable. This way we can use a simple indirection to disambiguate between them. For some reason this causes the `Ref` with the extra field access in `initprob`, so using `initdata` instead.

Make `get_initial_values` differentiate

---

src/initialization.jl
src/utils.jl

Reverts SciML/SciMLBase.jl#1025

Revert "Make `get_initial_values` differentiate"

---

ext/SciMLBaseChainRulesCoreExt.jl

This fixes https://github.com/SciML/SciMLSensitivity.jl/issues/1181

Add adjoint for ODEProblem constructor w/ iip, specialization

---

src/problems/linear_problems.jl
src/remake.jl
test/remake_tests.jl

@jClugstor this should fix your remake issue.

feat: implement `remake(::LinearProblem)`

---

src/problems/ode_problems.jl

feat: retain information in `SplitFunction` when adding `_func_cache`

---

src/solutions/ode_solutions.jl

Before this PR:
```julia
julia> SciMLBase.DEStats()
SciMLBase.DEStats
Number of function 1 evaluations:                  -1
Number of function 2 evaluations:                  -1
Number of W matrix evaluations:                    -1
Number of linear solves:                           -1
Number of Jacobians created:                       -1
Number of nonlinear solver iterations:             -1
Number of nonlinear solver convergence failures:   -1
Number of fixed-point solver iterations:                     -1
Number of fixed-point solver convergence failures:           -1
Number of …
```

fix printing of DEStats

---

src/scimlfunctions.jl

This PR fixes the following issue in running an SDE with a SciMLOperator
```julia
using LinearAlgebra
using StochasticDiffEq
using SciMLOperators
using SciMLOperators: AbstractSciMLOperator
using SciMLBase
using OrdinaryDiffEqTsit5
struct MyMatrixOperator{T, AT <: AbstractMatrix{T}} <: AbstractSciMLOperator{T}
A::AT
end
(L::MyMatrixOperator)(w, v, u, p, t) = mul!(w, L.A, v)
f = MyMatrixOperator(rand(2, 2))
g(du, u, p, t) = lmul!(0.1, du)
x0 = rand(2)
tspan = (0.0, 1.0)
prob = SDEProblem{true}(f, g, x0, tspan)
sol = solve(prob, SRIW1())
```
```julia
ERROR: MethodError: no method …
```

Add methods for SDEFunction in case of SciMLOperators v1+

---

src/initialization.jl
test/downstream/initialization.jl
test/initialization.jl

`nothing` is a perfectly valid nonlinear solver algorithm

---

src/SciMLBase.jl
src/function_wrappers.jl

We should probably move / remove those wrapped functions too, but another time.

Force more function specialization

---

src/solutions/ode_solutions.jl
test/downstream/ode_stripping.jl

fix: fix `strip_solution` for empty `ODEProblem` solutions

---

ext/SciMLBaseForwardDiffExt.jl
ext/SciMLBaseMooncakeExt.jl

Fixes https://github.com/SciML/SciMLBase.jl/issues/1119

Remove DiffEqBase reference from Mooncake Extension 

---

src/SciMLBase.jl
src/solve.jl

Upstreaming https://github.com/SciML/PreallocationTools.jl/blob/master/test/gpu_all.jl#L4-L5

Upstream `anyeltypedual` for `FixedSizeDiffCache`

---

src/errors.jl
src/solve.jl

fix: remove usages of TruncatedStacktraces

---

ext/SciMLBaseForwardDiffExt.jl
ext/SciMLBaseMakieExt.jl
src/alg_traits.jl
src/debug.jl
src/errors.jl
src/problems/bvp_problems.jl
src/problems/dae_problems.jl
src/problems/dde_problems.jl
src/problems/discrete_problems.jl
src/problems/implicit_discrete_problems.jl
src/problems/integral_problems.jl
src/problems/linear_problems.jl
src/problems/nonlinear_problems.jl
src/problems/ode_problems.jl
src/problems/optimization_problems.jl
src/problems/rode_problems.jl
src/problems/sdde_problems.jl
src/problems/sde_problems.jl
src/problems/steady_state_problems.jl
src/solutions/basic_solutions.jl
src/solutions/dae_solutions.jl
src/solutions/ode_solutions.jl
src/solutions/rode_solutions.jl
src/solve.jl

None applicable
Use `<`angle brackets`>` for when the hyperlink text is the URL itself, and update hyperlink targets.

Use markdown link syntax and update hyperlinks

---

src/problems/analytical_problems.jl
src/problems/bvp_problems.jl
src/problems/dae_problems.jl
src/problems/dde_problems.jl
src/problems/discrete_problems.jl
src/problems/implicit_discrete_problems.jl
src/problems/integral_problems.jl
src/problems/linear_problems.jl
src/problems/nonlinear_problems.jl
src/problems/ode_problems.jl
src/problems/optimization_problems.jl
src/problems/rode_problems.jl
src/problems/sdde_problems.jl
src/problems/sde_problems.jl
src/problems/steady_state_problems.jl

None applicable
Moves the type/constructor signature of Alias Specifier subtypes to the top of their respective docstrings. This allows Documenter.jl and terminal/REPL help viewer to pick it up as a signature, and follows convention of docstring order for better readability.

Move type/constructor signatures for alias types to top of docstrings

---

Project.toml
src/scimlfunctions.jl

Add `f_prototype` in `BVPFunction` for ODE/DAE variables and control variables in the optimal control problem.
Part of https://github.com/SciML/BoundaryValueDiffEq.jl/issues/336

Add f_prototype in BVPFunction
